version: '3.8'

services:

  postgresqldb:
    image: "postgres:11.5-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: tenpoDB


  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672


  eureka-server:
    build: architecture-registry-eureka/
    ports:
      - "8761:8761"


  api-gateway:
    build: architecture-api-gateway/
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server


  history-service:
    build: service-history/
    depends_on:
      - postgresqldb
      - eureka-server
    ports:
      - "8084:8084"


  user-service:
    build: service-user/
    depends_on:
      - postgresqldb
      - eureka-server
    ports:
      - "8081:8081"


  calculator-service:
    build: service-calculation/
    depends_on:
      - eureka-server
    ports:
      - "8083:8083"


  mock-service:
    build: service-mock/
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
   